"""Curated local-LLM list for the builder's model picker.

Only what the picker shows (see ``catalog.list_llm_models``): Ollama model id, display
label, domain, size class, and a rough RAM floor. The live Ollama probe supplies the
actually-installed set; this list is just curated suggestions.
"""

from typing import Any, Dict, List

CURATED_LOCAL_MODELS: List[Dict[str, Any]] = [
    {"id": "phi3:mini", "label": "Phi-3 Mini (3.8B)",
     "domain": "general", "size": "tiny", "min_ram_gb": 4},
    {"id": "gemma:2b", "label": "Gemma 2B", "domain": "general", "size": "tiny", "min_ram_gb": 3},
    {"id": "qwen2:1.5b", "label": "Qwen2 1.5B",
     "domain": "general", "size": "tiny", "min_ram_gb": 2},
    {"id": "tinyllama:1.1b", "label": "TinyLlama 1.1B",
     "domain": "general", "size": "tiny", "min_ram_gb": 1},
    {"id": "orca-mini:3b", "label": "Orca Mini 3B",
     "domain": "general", "size": "tiny", "min_ram_gb": 3},
    {"id": "mistral:7b-instruct", "label": "Mistral 7B Instruct",
     "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "mistral:7b-instruct-q4_0", "label": "Mistral 7B (Q4)",
     "domain": "general", "size": "small", "min_ram_gb": 4},
    {"id": "llama3:8b-instruct", "label": "Llama 3 8B Instruct",
     "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "llama3:8b-instruct-q4_0", "label": "Llama 3 8B (Q4)",
     "domain": "general", "size": "small", "min_ram_gb": 4},
    {"id": "llama3.1:8b", "label": "Llama 3.1 8B Instruct",
     "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "gemma:7b", "label": "Gemma 7B", "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "gemma:7b-instruct-q4_0", "label": "Gemma 7B (Q4)",
     "domain": "general", "size": "small", "min_ram_gb": 4},
    {"id": "qwen2:7b", "label": "Qwen2 7B", "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "qwen2:7b-instruct-q4_0", "label": "Qwen2 7B (Q4)",
     "domain": "general", "size": "small", "min_ram_gb": 4},
    {"id": "vicuna:7b", "label": "Vicuna 7B",
     "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "openchat:7b", "label": "OpenChat 7B",
     "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "neural-chat:7b", "label": "Neural Chat 7B",
     "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "starling-lm:7b", "label": "Starling 7B",
     "domain": "general", "size": "small", "min_ram_gb": 8},
    {"id": "meditron:7b", "label": "Meditron 7B (Medical - VERIFIED)",
     "domain": "medical", "size": "small", "min_ram_gb": 8},
    {"id": "codellama:7b-instruct", "label": "CodeLlama 7B",
     "domain": "code", "size": "small", "min_ram_gb": 8},
    {"id": "deepseek-coder:6.7b", "label": "DeepSeek Coder 6.7B",
     "domain": "code", "size": "small", "min_ram_gb": 8},
    {"id": "mixtral:8x7b", "label": "Mixtral 8x7B MoE",
     "domain": "general", "size": "medium", "min_ram_gb": 24},
    {"id": "mixtral:8x7b-instruct-q4_0", "label": "Mixtral 8x7B (Q4)",
     "domain": "general", "size": "medium", "min_ram_gb": 14},
    {"id": "solar:10.7b", "label": "SOLAR 10.7B",
     "domain": "general", "size": "medium", "min_ram_gb": 12},
    {"id": "codellama:13b-instruct", "label": "CodeLlama 13B",
     "domain": "code", "size": "medium", "min_ram_gb": 16},
    {"id": "wizardlm:13b", "label": "WizardLM 13B",
     "domain": "general", "size": "medium", "min_ram_gb": 16},
    {"id": "llama3:70b-instruct", "label": "Llama 3 70B Instruct",
     "domain": "general", "size": "large", "min_ram_gb": 48},
    {"id": "llama3:70b-instruct-q4_0", "label": "Llama 3 70B (Q4)",
     "domain": "general", "size": "large", "min_ram_gb": 28},
    {"id": "llama3.1:70b", "label": "Llama 3.1 70B Instruct",
     "domain": "general", "size": "large", "min_ram_gb": 48},
    {"id": "llama3.1:405b", "label": "Llama 3.1 405B",
     "domain": "general", "size": "xlarge", "min_ram_gb": 256},
]
