"""Backward-compatible shim: ``stage_graph`` was split into the ``graph/`` package.

Every name that used to live here is re-exported from ``evaluator.pipeline.graph`` so
``from evaluator.pipeline.stage_graph import X`` (and ``from evaluator.pipeline import
stage_graph as sg``) keep working unchanged. See ``graph/`` for the implementation:
``registry`` (node defs + artifacts), ``wiring`` (auto-wiring), ``cse``, ``branches``,
``modes``.
"""

from .graph import (  # noqa: F401  (re-export surface)
    ARTIFACT_CORPUS,
    ARTIFACT_GENERATED_ANSWERS,
    ARTIFACT_METRICS,
    ARTIFACT_QUERY_AUDIO,
    ARTIFACT_QUERY_TEXT,
    ARTIFACT_QUERY_VECTORS,
    ARTIFACT_AUDIO_QUERY_VECTORS,
    ARTIFACT_TEXT_QUERY_VECTORS,
    ARTIFACT_FUSED_QUERY_VECTORS,
    ARTIFACT_REFERENCE_TRANSCRIPTION,
    ARTIFACT_EMBEDDING_ALIGNMENT,
    ARTIFACT_RELEVANT_DOCS,
    ARTIFACT_RETRIEVED,
    ARTIFACT_SHORT_ANSWERS,
    ARTIFACT_CORPUS_VECTORS,
    ARTIFACT_VECTOR_INDEX,
    DATASET_ROLE_BOTH,
    DATASET_ROLE_CORPUS,
    DATASET_ROLE_QUESTIONS,
    GRAPH_TEMPLATE_SPECS,
    SOURCE_ARTIFACTS,
    OneOf,
    one_of,
    display_artifact_names,
    GraphTemplateSpec,
    StageGraph,
    StageNode,
    StageNodeDef,
    _DATASET_SOURCE_ROLE_OUTPUTS,
    _effective_inputs,
    _effective_outputs,
    dataset_columns,
    _freeze_params,
    _make_template_spec,
    assemble_specs,
    FeatureSet,
    _NODE_REGISTRY,
    _normalize_spec_item,
    _required_model_fields,
    _topo_order,
    _wire_nodes,
    build_branched_graph,
    build_graph_for_config,
    build_graph_from_spec,
    build_stage_graph,
    collapse_common_subexpressions,
    expand_branches,
    get_stage_node_def,
    register_stage_node,
    resolve_graph_template,
    validate_graph_artifacts,
)

__all__ = [
    "StageNode",
    "StageNodeDef",
    "StageGraph",
    "GraphTemplateSpec",
    "register_stage_node",
    "get_stage_node_def",
    "validate_graph_artifacts",
    "OneOf",
    "one_of",
    "display_artifact_names",
    "build_graph_from_spec",
    "collapse_common_subexpressions",
    "expand_branches",
    "build_branched_graph",
    "build_stage_graph",
    "build_graph_for_config",
    "resolve_graph_template",
    "GRAPH_TEMPLATE_SPECS",
    "DATASET_ROLE_BOTH",
    "DATASET_ROLE_CORPUS",
    "DATASET_ROLE_QUESTIONS",
    "SOURCE_ARTIFACTS",
    "ARTIFACT_CORPUS",
    "ARTIFACT_GENERATED_ANSWERS",
    "ARTIFACT_METRICS",
    "ARTIFACT_QUERY_AUDIO",
    "ARTIFACT_QUERY_TEXT",
    "ARTIFACT_QUERY_VECTORS",
    "ARTIFACT_AUDIO_QUERY_VECTORS",
    "ARTIFACT_TEXT_QUERY_VECTORS",
    "ARTIFACT_FUSED_QUERY_VECTORS",
    "ARTIFACT_REFERENCE_TRANSCRIPTION",
    "ARTIFACT_EMBEDDING_ALIGNMENT",
    "ARTIFACT_RELEVANT_DOCS",
    "ARTIFACT_RETRIEVED",
    "ARTIFACT_SHORT_ANSWERS",
    "ARTIFACT_CORPUS_VECTORS",
    "ARTIFACT_VECTOR_INDEX",
]
