"""Backward-compatible shim: ``stage_graph`` was split into the ``graph/`` package.

Every name that used to live here is re-exported from ``evaluator.pipeline.graph`` so
``from evaluator.pipeline.stage_graph import X`` (and ``from evaluator.pipeline import
stage_graph as sg``) keep working unchanged. See ``graph/`` for the implementation:
``registry`` (node defs + artifacts), ``wiring`` (auto-wiring), ``cse``, ``branches``,
``modes``.
"""

from .graph import (  # noqa: F401  (re-export surface)
    ARTIFACT_CORPUS,
    ARTIFACT_GENERATED_ANSWERS,
    ARTIFACT_METRICS,
    ARTIFACT_QUERY_AUDIO,
    ARTIFACT_QUERY_TEXT,
    ARTIFACT_QUERY_VECTORS,
    ARTIFACT_RELEVANT_DOCS,
    ARTIFACT_RETRIEVED,
    ARTIFACT_SHORT_ANSWERS,
    ARTIFACT_VECTOR_INDEX,
    DATASET_ROLE_BOTH,
    DATASET_ROLE_CORPUS,
    DATASET_ROLE_QUESTIONS,
    PIPELINE_MODE_SPECS,
    SOURCE_ARTIFACTS,
    PipelineModeSpec,
    StageGraph,
    StageNode,
    StageNodeDef,
    _config_rerank_enabled,
    _DATASET_SOURCE_ROLE_OUTPUTS,
    _effective_outputs,
    _freeze_params,
    _make_spec,
    _mode_node_ids,
    _NODE_REGISTRY,
    _normalize_spec_item,
    _required_model_fields,
    _topo_order,
    _wire_nodes,
    build_branched_graph,
    build_graph_for_config,
    build_graph_from_spec,
    build_stage_graph,
    collapse_common_subexpressions,
    expand_branches,
    get_stage_node_def,
    list_pipeline_mode_specs,
    register_stage_node,
    resolve_pipeline_mode_spec,
    validate_graph_artifacts,
)

__all__ = [
    "StageNode",
    "StageNodeDef",
    "StageGraph",
    "PipelineModeSpec",
    "register_stage_node",
    "get_stage_node_def",
    "validate_graph_artifacts",
    "build_graph_from_spec",
    "collapse_common_subexpressions",
    "expand_branches",
    "build_branched_graph",
    "build_stage_graph",
    "build_graph_for_config",
    "list_pipeline_mode_specs",
    "resolve_pipeline_mode_spec",
    "PIPELINE_MODE_SPECS",
    "DATASET_ROLE_BOTH",
    "DATASET_ROLE_CORPUS",
    "DATASET_ROLE_QUESTIONS",
    "SOURCE_ARTIFACTS",
    "ARTIFACT_CORPUS",
    "ARTIFACT_GENERATED_ANSWERS",
    "ARTIFACT_METRICS",
    "ARTIFACT_QUERY_AUDIO",
    "ARTIFACT_QUERY_TEXT",
    "ARTIFACT_QUERY_VECTORS",
    "ARTIFACT_RELEVANT_DOCS",
    "ARTIFACT_RETRIEVED",
    "ARTIFACT_SHORT_ANSWERS",
    "ARTIFACT_VECTOR_INDEX",
]
